# This configuration tells Netlify how to serve your TypeScript files.
# It sets the correct Content-Type header so the browser executes them as JavaScript.

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript"